### ISSUE TITLE
Request: improving plot_model function

### ISSUE THREAD

**Issue by mbbatukan** [sewkokot/opsvis#11]
Hi there, 

Thanks for the recent update. I was wondering if you could include a couple of options in plot_model function.

1. An option to remove all the nodes or elements from 2D or 3D plot (not node or element labels) to see just nodes or elements in the model.
2. An option for a section cut (2D elevation view - e.g. X=0m, Y=all, Z=all) in 3D model.

**Comment by sewkokot** [comment]
Hi @batukan009 
Thanks for the feature requests.
I implemented the first point, by adding arguments: nodes_only and fmt_model. The defaults are: nodes_only=False, fmt_model='b.-'. Examples:
```
opsv.plot_model(nodes_only=True)  # to show nodes only even thought the elements are defined
opsv.plot_model(fmt_model='b-')   # to show elements with no node markers
```
For the second point I need more time.

Update and test please!

**Comment by batukan009** [comment]
Thanks @sewkokot. These options work well. Looking forward to testing other implementations.

**Comment by sewkokot** [comment]
@mbbatukan Thank you for the dictionary suggestion. In the refactored latest opsvis package this feature is implemented and replaces the old string line formatting. See the updated examples and function documentation. Also please test!
