### ISSUE TITLE
Plotting errors

### ISSUE THREAD

**Issue by zubairwani17** [sewkokot/opsvis#21]
i am getting some errors with plotting with vfo and more
**AttributeError**: module 'vfo.internal_plotting_functions' has no attribute '_getAxisInfo'

**Comment by firai** [comment]
The vfo repo is at https://github.com/u-anurag/vfo.

**Comment by ZubairRWani** [comment]
some errors regarding animation and plots were solved. However, the previous problem persists 

File "C:\Users\Zubair\anaconda3\lib\site-packages\vfo\vfo.py", line 1302, in plot_fiberResponse2D
    axisIndex, axisXlabel = ipltf._getAxisInfo(LocalAxis)

**AttributeError**: module 'vfo.internal_plotting_functions' has no attribute '_getAxisInfo'

**Comment by firai** [comment]
Again, the vfo repo is at https://github.com/u-anurag/vfo. You will have better luck with getting answers to questions or issues about vfo at that repo.

**Comment by ZubairRWani** [comment]
Got it
