### ISSUE TITLE
circular patch fiber  section not included in the fib_sec_list_to_cmds function

### ISSUE THREAD

**Issue by BigDevil82** [sewkokot/opsvis#29]
Hello sir,
As indicated in the title, the circular fiber commands used in `plot_fiber_section` are not accounted in the `fib_sec_list_to_cmds ` function, both with `patch` and `layer` type. So if I use the circular patch command to create a fiber section, it won't be created if I  use `fib_sec_list_to_cmds` to do the work. It will lead to some unexpected results and the user can't notice it.
And for integrity, maybe a single `fiber` command should also be considered.

**Comment by sewkokot** [comment]
@BigDevil82 Thank you! I will update the `fib_sec_list_to_cmds` to support all options of the OpenSees 'Section Fiber' commands.

**Comment by sewkokot** [comment]
@BigDevil82 Ok, I have added both the 'patch circ' and 'layer circ' to `fib_sec_list_to_cmds`. Update the pip package, test and let me know if it works.

**Comment by BigDevil82** [comment]
@sewkokot Thank you, it works fine.
