### ISSUE TITLE
sig_out_per_node() Function

### ISSUE THREAD

**Issue by kamyarsa** [sewkokot/opsvis#33]
Hello,
I am trying to model soil continuum using quad element in Openseespy. I plotted the stress contour plot using the sig_out_per_node() function. I have two questions regarding this function.
1. Does this function use all four guass points in each element to represent the contours?
2. Is there any function to plot the displacement or strain contours like this?

In Advance, I am really grateful for your help!

**Comment by sewkokot** [comment]
Thank you for the questions.

1. The `plot_stress_2d` function uses the values at nodes which are extrapolated from the gauss points and then averaged between elements. I will update the documentation.
2. To plot the deformed structures use the `plot_defo` function. Strain contours are not implemented. I put it on my 'TODO' list.
