### ISSUE TITLE
Example "Animation of dynamic analysis and mode shapes of a 2d Portal Frame"

### ISSUE THREAD

**Issue by LjIA26** [sewkokot/opsvis#34]
Hello, 

the example "Animation of dynamic analysis and mode shapes of a 2d Portal Frame", when run doesn't plot any graphs. 

Run in sypder
Python = 3.9 
Openseespy = 3.4.0.2
Opsvis = 1.0.20

**Comment by sewkokot** [comment]
How do you run the example in Spyder, Jupyter or other method?

In Spyder or Jupyter notebook to get matplotlib animations write the command %matplotlib qt in the Ipython command window. By default only the static plots are displayed.

**Comment by Slopezre** [comment]
Hello Seweryn,

I was having the same issue (spyder), and I can see the animations with your instructions. Your contribution is greatly appreciated. Thanks!
