### ISSUE TITLE
plot_model() calls on non-existing commands in a more recent version of OpenSeesPy (3.8)

### ISSUE THREAD

**Issue by UzoUwaoma** [sewkokot/opsvis#37]
The current `plot_model` function calls on two functions from `OpenSeesPY` that do not exist. Can you please see to this?

The non-existent functions are:
* `ops.getNDM()[0]`
* `ops.getFixedNodes()`

Can you update these functions to reflect the current updates on `OpenSeesPy`.

**Comment by ccaprani** [comment]
This should be reopened - as far as I can see, the issue remains, e.g. https://github.com/sewkokot/opsvis/blob/c2df7c3ac7225bedd4f1e3c9eff4a0b3159bcafd/opsvis/model.py#L470

Oddly, openseespy minor-minor version 3.4.0.6 introduced this breaking change: https://openseespydoc.readthedocs.io/en/latest/src/changelog.html
