### ISSUE TITLE
Show load as magnitude because the direction is already shown

### ISSUE THREAD

**Issue by mhscott** [sewkokot/opsvis#39]
The plot_loads_2d function shows the proper direction of loads of negative magnitude, but the label still shows a negative value, implying a possible "double negative" interpretation, e.g., the -18.893 downward load shown below. My suggestion is to use abs() on the numbers after flipping the load arrows.

![image](https://user-images.githubusercontent.com/13142652/212556707-2e6ff813-51a8-4fd3-ad09-707c8b542d13.png)

**Comment by mhscott** [comment]
@sewkokot Looks like a simple fix, but wanted to run it by you before making a PR

**Comment by sewkokot** [comment]
@mhscott Thank you, indeed the double negative interpretation can be misleading. I will fix it and release a new version, this week.

**Comment by sewkokot** [comment]
@mhscott Please update the package and let me know if it works.
