### ISSUE TITLE
apply beamUniform eleload to a 3D element twice, the plot will be wrong

### ISSUE THREAD

**Issue by lvwanwan** [sewkokot/opsvis#47]
when apply one beamUniform eleload to a 3D element like this：ops.eleLoad('-ele', 1, '-type', '-beamUniform', -200,0,0)，the .section_force_diagram_3d('My', sfacM) is right ；but when i apply two beamUniform eleload to one 3D element like this：ops.eleLoad('-ele', 1, '-type', '-beamUniform', -200,0,0)，ops.eleLoad('-ele', 1, '-type', '-beamUniform', -200,0,0)，the .section_force_diagram_3d('My', sfacM) will be wrong.  i found the problem is when you calculate the j node force from i node force,you You only considered the last uniform load, thanks for  help to solve this issue

**Comment by sewkokot** [comment]
@lvwanwan, thank you for reporting this bug. Similar bug (ttps://github.com/sewkokot/opsvis/issues/40 ) for 2d frames was fixed, and now I'm working to fix the 3d one. I'll let you know when it's ready to update the package.

**Comment by sewkokot** [comment]
@lvwanwan It should be fixed now. Please test the updated package.

**Comment by lvwanwan** [comment]
Thank you very much for your modification，I have tested it ,the result is right, thanks again!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seweryn ***@***.***&gt;; 
发送时间: 2023年7月8日(星期六) 下午5:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sewkokot/opsvis] apply beamUniform eleload to a 3D element twice, the plot will be wrong (Issue #47)





 
@lvwanwan It should be fixed now. Please test the updated package.
