### ISSUE TITLE
getting error while plotting rectangular section

### ISSUE THREAD

**Issue by bahugunaashish** [sewkokot/opsvis#49]
I am getting the following error with the example provided at https://opsvis.readthedocs.io/en/latest/ex_plot_fiber_section.html could anyone help me out?
  
File ~\.conda\envs\py39\lib\site-packages\opsvis\fibsec.py:129 in plot_fiber_section
    poly = Polygon(zy, True, ec='k', fc=matcolor[matTag-1])

TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by mhscott** [comment]
@sewkokot Looks like `True` should be replaced with `closed=True` on line 129 of fibsec.py: https://github.com/sewkokot/opsvis/blob/master/opsvis/fibsec.py#L129

**Comment by sewkokot** [comment]
@mhscott, @bahugunaashish Thank you for reporting this issue and finding the solution. It seems it matplotlib incompatible changes - in matplotlib v3.6 it worked. It is fixed now in the pip package.
