### ISSUE TITLE
Rendering with only nodes, no elements

### ISSUE THREAD

**Issue by mhscott** [sewkokot/opsvis#5]
I think it's an easy fix for cases where there are only nodes and no elements

```
ops.node(1,0,-h/2)
ops.node(2,0,h/2)
ops.node(3,L,h/2)
ops.node(4,L,-h/2)

opsv.plot_model(node_labels=True)
```

![image](https://user-images.githubusercontent.com/13142652/143918492-eba47dbf-e68b-4861-93a7-7a48bdc13464.png)

**Comment by sewkokot** [comment]
@mhscott, I posponed the PR proposed by @BijanSeif for the refactored version, however, it takes longer than expected, so now I have merged the PR by @BijanSeif which solves this issue. Upgrade the opsvis and test, please!

**Comment by BijanSeif** [comment]
Hi Prof. @mhscott and @sewkokot. 
Just now I've tested the last released version for 2D and 3D plotting nodes without elements. **it is working correctly without any problem**.

**Comment by mhscott** [comment]
Same here, works well. Thanks!
