### ISSUE TITLE
interpFlag not active?

### ISSUE THREAD

**Issue by mhscott** [sewkokot/opsvis#6]
Working on a column buckling model--two frame elements and some zero length springs. With the default interpFlag=1
![image](https://user-images.githubusercontent.com/13142652/146680198-70ba2111-a165-4b36-aec4-e9273bb1501c.png)
With interpFlag=0 to remove the cubic interpolation, there is no displaced shape at all
![image](https://user-images.githubusercontent.com/13142652/146680240-19063556-0542-452f-95b5-79f6c8d34c3f.png)

**Comment by sewkokot** [comment]
@mhscott thank you for spotting this bug. It should be fixed now.

**Comment by mhscott** [comment]
Thanks, @sewkokot!
