### ISSUE TITLE
Missing support for ElasticTimoshenkoBeam

### ISSUE THREAD

**Issue by lucagrementieri** [sewkokot/opsvis#7]
The current code does not support ElasticTimoshenkoBeam.

In fact this element does not satisfy the `if` clause at https://github.com/sewkokot/opsvis/blob/master/src/opsvis/opsvis.py#L558.

Is it planned to add support to it?

**Comment by sewkokot** [comment]
@lucagrementieri thank you! It is fixed now. Update and check it out.

**Comment by lucagrementieri** [comment]
It works! Thank you!
